Repository Nordix/metal3-dev-tools, pull requests merged in 2023-06, with the labels that each got.

#678 Adding openstack plugin to packer
  resources/docker/builder/Dockerfile
Labels: size/XS, approved, lgtm

#680 Switch dev-tools integration pipeline to use dynamic workers
  ci/jobs/metal3_dev_tools_integration_tests.pipeline
Labels: size/XS, approved, lgtm

#681 ironic image patching removed
  ci/scripts/image_scripts/run_build_ironic.sh
Labels: size/S, approved, lgtm

#683 Add qemu-img package to image-builder container image
  resources/docker/builder/Dockerfile
Labels: size/XS, approved, lgtm

#682 Verify node image is not corrupted
  ci/scripts/image_scripts/upload_node_image_rt.sh
Labels: size/S, approved, lgtm

#679 Backup node images
  ci/jobs/openstack_node_image_building.pipeline
  ci/scripts/image_scripts/backup_node_images.sh
Labels: size/M, approved, lgtm

#684 Fix typo on backup_node_image.sh file name
  ci/scripts/image_scripts/backup_node_image.sh
Labels: size/XS, approved, lgtm

#685 Fix backup node image
  ci/scripts/image_scripts/backup_node_image.sh
Labels: size/M, approved, lgtm
