Repository Nordix/metal3-dev-tools, pull requests merged in 2023-12, with the labels that each got.

#727 add community repo, and CAPI and CAPO new release branches for sync
  scripts/update-nordix-repos-master.sh
Labels: size/M, approved, lgtm

#729 Cleanup unused linter test related files
  Makefile
  ci/jobs/docker_image_building.pipeline
  ci/jobs/linter_tests.pipeline
  ci/scripts/image_scripts/artifact_cleanup.sh
  configs/linter/.mdstylerc.rb
  resources/docker/linter/Dockerfile
  resources/docker/linter/golang/Dockerfile
  scripts/go-linter.sh
Labels: approved, lgtm, size/L

#732 add ironic-image release branches to be synced
  scripts/update-nordix-repos-master.sh
Labels: size/XS, approved, lgtm
