Repository Nordix/metal3-dev-tools, pull requests merged in 2023-03, with the labels that each got.

#656 add ironic-hwiri to repo sync
  scripts/update-nordix-repos-master.sh
Labels: size/M, approved, lgtm

#657 add mariadb-image repo sync
  scripts/update-nordix-repos-master.sh
Labels: size/S, approved, lgtm

#660 renovate: remove fmuyassarov from assignees
  renovate.json
Labels: size/XS, approved

#661 fix centos image registry url
  ci/scripts/image_scripts/source_cluster_container_images.sh
Labels: size/XS, approved, lgtm

#655 Update setting OS repos and keys since depreciation of apt-key
  ci/scripts/image_scripts/install_crio_on_ubuntu.sh
  ci/scripts/image_scripts/provision_node_image_ubuntu.sh
  ci/scripts/image_scripts/setup_docker_ubuntu.sh
Labels: size/S, approved, lgtm
