Repository Nordix/metal3-dev-tools, pull requests merged in 2023-10, with the labels that each got.

#705 align node image building with packer "retry" workflow
  ci/images/gen_metal3_centos_image.sh
  ci/scripts/image_scripts/provision_node_image_centos.sh
  ci/scripts/image_scripts/provision_node_image_ubuntu.sh
Labels: size/S, approved, lgtm

#704 add utility-images repo to repo syncing
  scripts/update-nordix-repos-master.sh
Labels: size/S, approved, lgtm

#709 update ubuntu source image used for base image
  ci/images/gen_base_ubuntu_image.sh
Labels: size/XS, approved, lgtm

#710 Revert back ubuntu base image to ubuntu-22.04-server-cloudimg-amd64_01_09_22
  ci/images/gen_base_ubuntu_image.sh
Labels: size/XS, approved, lgtm

#707 Add ci pipeline to build container images
  Makefile
  ci/jobs/container_image_building.pipeline
  scripts/build-container-image.sh
Labels: approved, lgtm, size/L

#711 add BMO release branches to sync
  scripts/update-nordix-repos-master.sh
Labels: size/XS, approved, lgtm

#715 Bump ubuntu vanilla image to latest build 18-10-23
  ci/images/gen_base_ubuntu_image.sh
  ci/images/gen_metal3_ubuntu_image.sh
  wow/Upgrade-image.md
Labels: size/XS, approved, lgtm

#716 Remove unnecessary copy of crictl binary
  ci/scripts/image_scripts/install_crio_on_centos.sh
  ci/scripts/image_scripts/provision_node_image_centos.sh
Labels: size/XS, approved, lgtm

#714 Change the credentials use for quay in container image build pipeline
  ci/jobs/container_image_building.pipeline
Labels: size/XS, approved, lgtm

#719 disable sshd ClientAlive requests for baseimage
  ci/scripts/image_scripts/hardening_base_image.sh
Labels: size/XS, approved, lgtm
