Repository Nordix/metal3-dev-tools, pull requests merged in 2023-09, with the labels that each got.

#695 correct IPA source path used during building
  ci/scripts/image_scripts/build_ipa.sh
Labels: size/XS, approved, lgtm

#694 Add huutomerkki to assignees list and fix renovate config
  renovate.json
Labels: size/XS, approved, lgtm

#702 Add libvirt to Jenkins images
  ci/scripts/image_scripts/provision_jumphost_jenkins_base_img.sh
Labels: size/XS, approved, lgtm

#701 Add script to build, push and cleanup container images
  scripts/build-container-image.sh
  scripts/files/container_image_names.json
Labels: approved, lgtm, size/L

#700 Backup metal3 images
  ci/images/gen_metal3_centos_image.sh
  ci/images/gen_metal3_ubuntu_image.sh
  ci/scripts/openstack/utils.sh
Labels: size/M, approved, lgtm
