Repository Nordix/metal3-dev-tools, pull requests merged in 2023-11, with the labels that each got.

#717 Rename variable for branch name in container-build pipeline
  ci/jobs/container_image_building.pipeline
Labels: size/XS, approved, lgtm

#723 Migrate to k8s community-owned repos.
  ci/scripts/image_scripts/provision_node_image_centos.sh
  ci/scripts/image_scripts/provision_node_image_ubuntu.sh
  ci/scripts/image_scripts/target_cluster_container_images.sh
Labels: size/M, approved, lgtm

#720 pin builder and linter Docker images
  resources/docker/builder/Dockerfile
Labels: size/XS, approved, lgtm

#725 pin the main Python image as well
  resources/docker/builder/Dockerfile
Labels: size/XS, approved, lgtm

#722 image building improvements
  ci/images/gen_metal3_ubuntu_image.sh
Labels: size/S, approved, lgtm
