Repository Nordix/metal3-dev-tools, pull requests merged in 2023-08, with the labels that each got.

#691 Bump k8s version to v1.28.1
  ci/images/README.md
  ci/images/gen_metal3_centos_image.sh
  ci/images/gen_metal3_ubuntu_image.sh
  ci/images/run_local.sh
  ci/jobs/metal3_dev_tools_integration_tests.pipeline
  ci/scripts/image_scripts/backup_node_image.sh
  ci/scripts/image_scripts/install_crio_on_centos.sh
  ci/scripts/image_scripts/install_crio_on_ubuntu.sh
  ci/scripts/image_scripts/provision_node_image_centos.sh
  ci/scripts/image_scripts/provision_node_image_ubuntu.sh
  ci/scripts/image_scripts/source_cluster_container_images.sh
  ci/scripts/image_scripts/upload_node_image_rt.sh
  renovate.json
Labels: size/M, approved, lgtm

#690 Share metal3 image to dev2 project after successful build
  ci/jobs/openstack_image_building.pipeline
  ci/scripts/image_scripts/share_image.sh
  ci/scripts/openstack/utils.sh
Labels: approved, lgtm, size/L

#692 add release-1.5 branches to sync
  scripts/update-nordix-repos-master.sh
Labels: size/XS, approved, lgtm
