Repository Nordix/metal3-dev-tools, pull requests merged in 2024-01, with the labels that each got.

#724 Container building pipeline: supports git tags and remove local image info database
  ci/jobs/container_image_building.pipeline
  scripts/build-container-image.sh
  scripts/files/container_image_names.json
Labels: approved, lgtm, size/L

#735 Add release-1.6 branch updates for CAPM3 and IPAM and release-0.5 branch for BMO
  scripts/update-nordix-repos-master.sh
Labels: size/XS, approved, lgtm

#736 stop syncing EOL release branches to Nordix
  scripts/update-nordix-repos-master.sh
Labels: size/XS, approved, lgtm

#734 Bump k8s to v1.29.0
  ci/images/README.md
  ci/images/gen_metal3_centos_image.sh
  ci/images/gen_metal3_ubuntu_image.sh
  ci/images/run_local.sh
  ci/jobs/metal3_dev_tools_integration_tests.pipeline
  ci/scripts/image_scripts/backup_node_image.sh
  ci/scripts/image_scripts/install_crio_on_centos.sh
  ci/scripts/image_scripts/install_crio_on_ubuntu.sh
  ci/scripts/image_scripts/provision_node_image_centos.sh
  ci/scripts/image_scripts/provision_node_image_ubuntu.sh
  ci/scripts/image_scripts/source_cluster_container_images.sh
  ci/scripts/image_scripts/upload_node_image_rt.sh
Labels: size/M, approved, lgtm

#738 add capo release-0.9 branch for syncing
  scripts/update-nordix-repos-master.sh
Labels: size/XS, approved, lgtm

#739 downgrade packer to 1.9.2
  resources/docker/builder/Dockerfile
Labels: size/XS, approved, lgtm

#743 switch markdownlint container to markdownlint-cli2
  .markdownlint-cli2.yaml
  README.md
  ci/images/README.md
  ci/scripts/openstack/README.md
  getting-started.md
  hack/markdownlint.sh
  tools/scalability/README.md
  tools/setup_machines/README.md
  wow/Upgrade-image.md
  wow/citycloud.md
  wow/fullstack-build.md
  wow/github-workflow.md
  wow/jenkins_ci/README.md
Labels: approved, lgtm, size/XL
