Repository Nordix/metal3-dev-tools, pull requests merged in 2024-04, with the labels that each got.

#758 add ironic-image 24.1 release branch to sync
  scripts/update-nordix-repos-master.sh
Labels: size/XS, approved, lgtm

#748 Remove folder wow moved to metal3-clusterapi-docs
  wow/Upgrade-image.md
  wow/citycloud.md
  wow/fullstack-build.md
  wow/github-workflow.md
  wow/jenkins_ci/README.md
  wow/jenkins_ci/jenkins-check-ci.sh
  wow/jenkins_ci/ssh.png
Labels: approved, lgtm, size/XL

#751 Remove tools moved to metal3-clusterapi-docs
  tools/ironic-python-agent-image/README.md
  tools/ironic-python-agent-image/unpack-ipa-archive.sh
  tools/scalability/README.md
  tools/scalability/setup_vms.sh
  tools/scalability/vm_ip_list.txt
Labels: approved, lgtm, size/L

#761 Add support for release-1.7 syncing to Nordix
  scripts/update-nordix-repos-master.sh
Labels: size/S, approved, lgtm
